In [92]:
import pandas as pd
import numpy as np
import pathlib as Path
import re

In [23]:
# print(Path().absolute())
# dataset_path = Path().absolute() / "data"
df = pd.read_table("../data/spambase.data", sep=",", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [24]:
print(df.shape)

(4601, 58)

In [25]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4601 non-null   float64
 1   1       4601 non-null   float64
 2   2       4601 non-null   float64
 3   3       4601 non-null   float64
 4   4       4601 non-null   float64
 5   5       4601 non-null   float64
 6   6       4601 non-null   float64
 7   7       4601 non-null   float64
 8   8       4601 non-null   float64
 9   9       4601 non-null   float64
 10  10      4601 non-null   float64
 11  11      4601 non-null   float64
 12  12      4601 non-null   float64
 13  13      4601 non-null   float64
 14  14      4601 non-null   float64
 15  15      4601 non-null   float64
 16  16      4601 non-null   float64
 17  17      4601 non-null   float64
 18  18      4601 non-null   float64
 19  19      4601 non-null   float64
 20  20      4601 non-null   float64
 21  21      4601 non-null   float64
 22  22      4601 non-null   float64
 23  23      4601 non-null   float64
 24  24      4601 non-null   float64
 25  25      4601 non-null   float64
 26  26      4601 non-null   float64
 27  27      4601 non-null   float64
 28  28      4601 non-null   float64
 29  29      4601 non-null   float64
 30  30      4601 non-null   float64
 31  31      4601 non-null   float64
 32  32      4601 non-null   float64
 33  33      4601 non-null   float64
 34  34      4601 non-null   float64
 35  35      4601 non-null   float64
 36  36      4601 non-null   float64
 37  37      4601 non-null   float64
 38  38      4601 non-null   float64
 39  39      4601 non-null   float64
 40  40      4601 non-null   float64
 41  41      4601 non-null   float64
 42  42      4601 non-null   float64
 43  43      4601 non-null   float64
 44  44      4601 non-null   float64
 45  45      4601 non-null   float64
 46  46      4601 non-null   float64
 47  47      4601 non-null   float64
 48  48      4601 non-null   float64
 49  49      4601 non-null   float64
 50  50      4601 non-null   float64
 51  51      4601 non-null   float64
 52  52      4601 non-null   float64
 53  53      4601 non-null   float64
 54  54      4601 non-null   float64
 55  55      4601 non-null   int64
 56  56      4601 non-null   int64
 57  57      4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB
None

In [87]:
headers = pd.read_csv('../data/spambase_headers.csv', header = 0, index_col=False).squeeze();
headers = headers.columns.tolist()
df.columns = headers
df.head(10)

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,is_spam
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
5,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1
6,0.00,0.00,0.00,0.0,1.92,0.00,0.00,0.00,0.00,0.64,...,0.00,0.054,0.0,0.164,0.054,0.000,1.671,4,112,1
7,0.00,0.00,0.00,0.0,1.88,0.00,0.00,1.88,0.00,0.00,...,0.00,0.206,0.0,0.000,0.000,0.000,2.450,11,49,1
8,0.15,0.00,0.46,0.0,0.61,0.00,0.30,0.00,0.92,0.76,...,0.00,0.271,0.0,0.181,0.203,0.022,9.744,445,1257,1
9,0.06,0.12,0.77,0.0,0.19,0.32,0.38,0.00,0.06,0.00,...,0.04,0.030,0.0,0.244,0.081,0.000,1.729,43,749,1

In [90]:
df["is_spam"].value_counts(normalize=True)

0    0.605955
1    0.394045
Name: is_spam, dtype: float64

In [93]:
for col in df.columns[:-1]:
        df[col] = df[col] / df[col].max()

        # Rename columns to remove prefix/suffix
        new_col_name = re.sub('^word_freq_|^char_freq_|^capital_run_length_', '', col)
        df = df.rename(columns={col: new_col_name})

df.head()

,make,address,all,3d,our,over,remove,internet,order,mail,...,;,(,[,!,$,#,average,longest,total,is_spam
0,0.000000,0.044818,0.125490,0.0,0.032,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.023955,0.000000,0.000000,0.003407,0.006107,0.017549,1
1,0.046256,0.019608,0.098039,0.0,0.014,0.047619,0.028886,0.006301,0.000000,0.051705,...,0.000000,0.013536,0.0,0.011454,0.029985,0.002421,0.004639,0.010111,0.064895,1
2,0.013216,0.000000,0.139216,0.0,0.123,0.032313,0.026135,0.010801,0.121673,0.013751,...,0.002281,0.014664,0.0,0.008498,0.030651,0.000504,0.008908,0.048553,0.142605,1
3,0.000000,0.000000,0.000000,0.0,0.063,0.000000,0.042641,0.056706,0.058935,0.034653,...,0.000000,0.014048,0.0,0.004218,0.000000,0.000000,0.003208,0.004004,0.012057,1
4,0.000000,0.000000,0.000000,0.0,0.063,0.000000,0.042641,0.056706,0.058935,0.034653,...,0.000000,0.013843,0.0,0.004157,0.000000,0.000000,0.003208,0.004004,0.012057,1